# Generated by Django 3.1 on 2020-09-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet2',
        ),
    ]
